force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Competency__c/Competency__c.object-meta.xml
<CustomObject>
    <label>Competency</label>
    <nameField>
        <label>Competency  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competencys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competency__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Competencys</relationshipLabel>
    <relationshipName>Competencys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Education__c/Education__c.object-meta.xml
<CustomObject>
    <label>Education</label>
    <nameField>
        <label>Education Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Educations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Education__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Educations</relationshipLabel>
    <relationshipName>Educations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Key_Expertise__c/Key_Expertise__c.object-meta.xml
<CustomObject>
    <label>Key Expertise</label>
    <nameField>
        <label>Key Expertise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Expertises</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Key_Expertise__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Key Expertises</relationshipLabel>
    <relationshipName>Key_Expertises</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reference__c/Reference__c.object-meta.xml
<CustomObject>
    <label>Reference</label>
    <nameField>
        <label>Reference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>References</relationshipLabel>
    <relationshipName>References</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Social_Handle__c/Social_Handle__c.object-meta.xml
<CustomObject>
    <label>Social Handle</label>
    <nameField>
        <label>Social Handle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social HandleS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Handle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Social HandleS</relationshipLabel>
    <relationshipName>Social_HandleS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trailhead_Superbadge__c/Trailhead_Superbadge__c.object-meta.xml
<CustomObject>
    <label>Trailhead Superbadge</label>
    <nameField>
        <label>Trailhead Superbadge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailhead SuperbadgeS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trailhead_Superbadge__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trailhead SuperbadgeS</relationshipLabel>
    <relationshipName>Trailhead_SuperbadgeS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/Work_Experience__c.object-meta.xml
<CustomObject>
    <label>Work Experience</label>
    <nameField>
        <label>Work Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work ExperienceS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Experience__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Work ExperienceS</relationshipLabel>
    <relationshipName>Work_ExperienceS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CvInformeshonTest.cls
@isTest
private class CvInformeshonTest {
    @testSetup static void dataSetup() {
        
        contact co = new contact();
        co.LastName = 'test';
        
        insert co;
        
        Certification__c cer = new Certification__c();
        cer.Name = 'test';
        cer.Contact__c = co.id;
        
        insert cer;
        
        Work_Experience__c work = new Work_Experience__c();
        work.Name = 'test';
        work.Contact__c = co.id;
        
        insert work;
        
        Social_Handle__c socail = new Social_Handle__c();
        socail.Name = 'test';
        socail.Contact__c = co.id;
        
        insert socail;
        
        Trailhead_Superbadge__c trail = new Trailhead_Superbadge__c();
        trail.Name = 'test';
        trail.Contact__c = co.id;
        
        insert trail;
        
        Education__c educa = new Education__c();
        educa.Name = 'test';
        educa.Contact__c = co.id;
        
        insert educa;
        
        Key_Expertise__c key = new Key_Expertise__c();
        key.Name = 'test';
        key.Contact__c = co.id;
        
        insert key;
        
        Reference__c ref = new Reference__c();
        ref.Name = 'test';
        ref.Contact__c = co.id;
        
        insert ref;
        
        Competency__c comp = new Competency__c();
        comp.Name = 'test';
        comp.Contact__c = co.id;
        
        insert comp;
        
        
    }  
    
    @isTest static void unitTest1() {
        Contact co = [SELECT id, LastName FROM COntact WHERE LastName = 'test' LIMIT 1];
        test.startTest();
        CvInformeshon.getContact(co.id);
        CvInformeshon.getCertification(co.id);
        CvInformeshon.getWorkExperience(co.id);
        CvInformeshon.getSocialHandle(co.id);
        CvInformeshon.getTrailheadSuperbadge(co.id);
        CvInformeshon.getEducation(co.id);
        CvInformeshon.getKeyExpertise(co.id);
        CvInformeshon.getReference(co.id);
        CvInformeshon.getAllAccountsByRating(co.id);
        test.stopTest();
        
    }
    
}