force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <label>Release</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Competency__c/Competency__c.object-meta.xml
<CustomObject>
    <label>Competency</label>
    <nameField>
        <label>Competency  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competencys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competency__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Competencys</relationshipLabel>
    <relationshipName>Competencys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Competency__c/fields/Score1__c.field-meta.xml
<CustomField>
    <fullName>Score1__c</fullName>
    <label>Score1</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Formatted_Address__c.field-meta.xml
<CustomField>
    <fullName>Formatted_Address__c</fullName>
    <formula>MailingCity + MailingCountry + MailingState + MailingStreet + MailingPostalCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Formatted_Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Education__c/Education__c.object-meta.xml
<CustomObject>
    <label>Education</label>
    <nameField>
        <label>Education Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Educations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Education__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Educations</relationshipLabel>
    <relationshipName>Educations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Education__c/fields/GPA__c.field-meta.xml
<CustomField>
    <fullName>GPA__c</fullName>
    <label>GPA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Key_Expertise__c/Key_Expertise__c.object-meta.xml
<CustomObject>
    <label>Key Expertise</label>
    <nameField>
        <label>Key Expertise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Expertises</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Key_Expertise__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Key Expertises</relationshipLabel>
    <relationshipName>Key_Expertises</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Key_Expertise__c/fields/Score_Out_of_100__c.field-meta.xml
<CustomField>
    <fullName>Score_Out_of_100__c</fullName>
    <label>Score (Out of 100)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reference__c/Reference__c.object-meta.xml
<CustomObject>
    <label>Reference</label>
    <nameField>
        <label>Reference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>References</relationshipLabel>
    <relationshipName>References</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reference__c/fields/MailTo__c.field-meta.xml
<CustomField>
    <fullName>MailTo__c</fullName>
    <formula>Link__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MailTo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Handle__c/Social_Handle__c.object-meta.xml
<CustomObject>
    <label>Social Handle</label>
    <nameField>
        <label>Social Handle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social HandleS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Handle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Social HandleS</relationshipLabel>
    <relationshipName>Social_HandleS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Social_Handle__c/fields/Handle_Icon__c.field-meta.xml
<CustomField>
    <fullName>Handle_Icon__c</fullName>
    <label>Handle Icon</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Social_Handle__c/fields/Handle_Link__c.field-meta.xml
<CustomField>
    <fullName>Handle_Link__c</fullName>
    <label>Handle Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trailhead_Superbadge__c/Trailhead_Superbadge__c.object-meta.xml
<CustomObject>
    <label>Trailhead Superbadge</label>
    <nameField>
        <label>Trailhead Superbadge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailhead SuperbadgeS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trailhead_Superbadge__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trailhead SuperbadgeS</relationshipLabel>
    <relationshipName>Trailhead_SuperbadgeS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trailhead_Superbadge__c/fields/Favourite__c.field-meta.xml
<CustomField>
    <fullName>Favourite__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Favourite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trailhead_Superbadge__c/fields/Superbadge_Description__c.field-meta.xml
<CustomField>
    <fullName>Superbadge_Description__c</fullName>
    <label>Superbadge Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trailhead_Superbadge__c/fields/Superbadge_Image__c.field-meta.xml
<CustomField>
    <fullName>Superbadge_Image__c</fullName>
    <label>Superbadge Image</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Trailhead_Superbadge__c/fields/Superbadge_Link__c.field-meta.xml
<CustomField>
    <fullName>Superbadge_Link__c</fullName>
    <label>Superbadge Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/Work_Experience__c.object-meta.xml
<CustomObject>
    <label>Work Experience</label>
    <nameField>
        <label>Work Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work ExperienceS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Experience__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Work ExperienceS</relationshipLabel>
    <relationshipName>Work_ExperienceS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>Responsibilities__c</fullName>
    <label>Responsibilities</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CvInformeshon.cls
public class CvInformeshon {
    @AuraEnabled(cacheable=true)
    
    public static Contact getContact(String recordId){
        // system.debug('accId >> ' + recordId);
        Contact conlist =[SELECT Id, Name,Title,Photo_URL__c,Profile__c,Address__c, Email, Phone, Formatted_Address__c, LastName,FirstName FROM Contact where id =: recordId];
        //system.debug(conlist);
        return conlist;       
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Certification__c> getCertification(String recordId){
        // system.debug('accId >> ' + recordId);
        List<Certification__c> cerlist =[SELECT Id, Name, Contact__c, Release__c,Order__c FROM Certification__c WHERE Contact__c =: recordId];
        system.debug(cerlist);
        return cerlist;      
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Work_Experience__c> getWorkExperience(String recordId){
        // system.debug('accId >> ' + recordId);
        List<Work_Experience__c> workList =[SELECT Id, Name, Company__c, Contact__c, Duration__c,Responsibilities__c FROM Work_Experience__c WHERE Contact__c =: recordId];
        //system.debug(cerlist);
        return workList;     
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Social_Handle__c> getSocialHandle(String recordId){
        // system.debug('accId >> ' + recordId);
        List<Social_Handle__c> socilList =[SELECT Id, Name, Handle_Icon__c, Contact__c, Handle_Link__c FROM Social_Handle__c WHERE Contact__c =: recordId];
        //system.debug(cerlist);
        return socilList;       
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Trailhead_Superbadge__c> getTrailheadSuperbadge(String recordId){
        // system.debug('accId >> ' + recordId);
        List<Trailhead_Superbadge__c> trailheadList =[SELECT Id, Name, Favourite__c, Contact__c, Superbadge_Description__c,Superbadge_Image__c,Superbadge_Link__c FROM Trailhead_Superbadge__c WHERE Contact__c =: recordId];
        system.debug(trailheadList);
        return trailheadList;       
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Education__c> getEducation(String recordId){
        List<Education__c> EducaList =[SELECT Id, Name, GPA__c, Contact__c, School_Name__c, Duration__c FROM Education__c WHERE Contact__c =: recordId];
        
        return EducaList;       
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Key_Expertise__c> getKeyExpertise(String recordId){
        List<Key_Expertise__c> keyList =[SELECT Id, Name, Score_Out_of_100__c, Contact__c FROM Key_Expertise__c WHERE Contact__c =: recordId];
        
        return keyList;       
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Reference__c> getReference(String recordId){
        List<Reference__c> referList =[SELECT Id, Name,Link__c, Company__c,Photo_URL__c,Relationship__c,MailTo__c, Contact__c FROM Reference__c WHERE Contact__c =: recordId];
        
        return referList;       
    }
    
    @AuraEnabled(cacheable=true)
    public static List<DataSet> getAllAccountsByRating(String recordId){
        List<AggregateResult> result =  [Select Count(Id) cnt, Score1__c from Competency__c  WHERE Contact__c =: recordId  group by  Score1__c];
        List<DataSet> dataSet = new List<DataSet>();
        for(AggregateResult ar:result){
            String status =  (String)ar.get('Score1__c') ;
            Integer total =(Integer)ar.get('cnt');
            dataSet.add(new DataSet(status ,total));
        }
        System.debug('dataSet'+dataSet);
        return dataSet ;
    }
    public class DataSet{
        public DataSet(String label ,Integer count){
            this.label  = label ;
            this.count = count ;
        }
        @AuraEnabled
        public String label {get;set;}
        @AuraEnabled
        public Integer  count {get;set;}
    }
}